apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: application
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  selector:
    matchLabels:
      app: application
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: application
        tier: frontend
    spec:
      containers:
      - image: ==DOCKER_USERNAME==/simple-application:==DEPLOYMENT_STAMP==
        name: application
        env:
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: application-mysql.default.svc.cluster.local
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_INSTANCE_NAME
          value: "mysql"
        ports:
        - containerPort: 3000
          name: application
